enum ExpenseCategoryType {
  shops,
  house,
  cafe,
  it,
  auto,
  clothes,
  fun,
  gifts,
  trips,
  education,
  medicine,
  services,
  charity,
  credits,
  debts,
}

const EXPENSE_CATEGORY_FROM_DB_MAPPING = {
  "shops": ExpenseCategoryType.shops,
  "house": ExpenseCategoryType.house,
  "cafe": ExpenseCategoryType.cafe,
  "it": ExpenseCategoryType.it,
  "auto": ExpenseCategoryType.auto,
  "clothes": ExpenseCategoryType.clothes,
  "fun": ExpenseCategoryType.fun,
  "gifts": ExpenseCategoryType.gifts,
  "trips": ExpenseCategoryType.trips,
  "education": ExpenseCategoryType.education,
  "medicine": ExpenseCategoryType.medicine,
  "services": ExpenseCategoryType.services,
  "charity": ExpenseCategoryType.charity,
  "credits": ExpenseCategoryType.credits,
  "debts": ExpenseCategoryType.debts,
};

const EXPENSE_CATEGORY_TO_DB_MAPPING = {
  ExpenseCategoryType.shops: "shops",
  ExpenseCategoryType.house: "house",
  ExpenseCategoryType.cafe: "cafe",
  ExpenseCategoryType.it: "it",
  ExpenseCategoryType.auto: "auto",
  ExpenseCategoryType.clothes: "clothes",
  ExpenseCategoryType.fun: "fun",
  ExpenseCategoryType.gifts: "gifts",
  ExpenseCategoryType.trips: "trips",
  ExpenseCategoryType.education: "education",
  ExpenseCategoryType.medicine: "medicine",
  ExpenseCategoryType.services: "services",
  ExpenseCategoryType.charity: "charity",
  ExpenseCategoryType.credits: "credits",
  ExpenseCategoryType.debts: "debts",
};
