enum IncomeCategoryType {
  salary,
  prepaid,
  bounty,
  royalty,
  rent,
  business,
  investments,
  dividends,
  coupons,
  deposits,
  insurance,
  debts,
  tax_deductions,
  pension,
  gos_support,
  gifts,
}

const INCOME_CATEGORY_FROM_DB_MAPPING = {
  "salary": IncomeCategoryType.salary,
  "prepaid": IncomeCategoryType.prepaid,
  "bounty": IncomeCategoryType.bounty,
  "royalty": IncomeCategoryType.royalty,
  "rent": IncomeCategoryType.rent,
  "business": IncomeCategoryType.business,
  "investments": IncomeCategoryType.investments,
  "dividends": IncomeCategoryType.dividends,
  "coupons": IncomeCategoryType.coupons,
  "deposits": IncomeCategoryType.deposits,
  "insurance": IncomeCategoryType.insurance,
  "debts": IncomeCategoryType.debts,
  "tax_deductions": IncomeCategoryType.tax_deductions,
  "pension": IncomeCategoryType.pension,
  "gos_support": IncomeCategoryType.gos_support,
  "gifts": IncomeCategoryType.gifts,
};

const INCOME_CATEGORY_TO_DB_MAPPING = {
  IncomeCategoryType.salary: "salary",
  IncomeCategoryType.prepaid: "prepaid",
  IncomeCategoryType.bounty: "bounty",
  IncomeCategoryType.royalty: "royalty",
  IncomeCategoryType.rent: "rent",
  IncomeCategoryType.business: "business",
  IncomeCategoryType.investments: "investments",
  IncomeCategoryType.dividends: "dividends",
  IncomeCategoryType.coupons: "coupons",
  IncomeCategoryType.deposits: "deposits",
  IncomeCategoryType.insurance: "insurance",
  IncomeCategoryType.debts: "debts",
  IncomeCategoryType.tax_deductions: "tax_deductions",
  IncomeCategoryType.pension: "pension",
  IncomeCategoryType.gos_support: "gos_support",
  IncomeCategoryType.gifts: "gifts",
};
